# Generated by Django 3.2.25 on 2025-09-06 01:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cenarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cod', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('periodo_anterior', models.PositiveIntegerField(default=0)),
                ('periodo_atual', models.PositiveIntegerField(default=0)),
                ('status_decisoes_disponiveis', models.BooleanField(default=False)),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='cenarios.cenario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jogo',
            constraint=models.CheckConstraint(check=models.Q(('periodo_atual__gte', 0)), name='jogo_periodo_atual_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='jogo',
            constraint=models.CheckConstraint(check=models.Q(('periodo_anterior__gte', 0)), name='jogo_periodo_anterior_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='jogo',
            constraint=models.CheckConstraint(check=models.Q(('periodo_anterior__lte', django.db.models.expressions.F('periodo_atual'))), name='jogo_periodo_anterior_lte_atual'),
        ),
    ]
