# Generated by Django 3.2.25 on 2025-09-06 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='name',
            new_name='nome',
        ),
    ]
