# Generated by Django 3.2.25 on 2025-09-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cenarios', '0004_alter_cenario_produto'),
        ('jogos', '0002_rename_name_jogo_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='cenario',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='cenarios.cenario'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='cod',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
