# Generated by Django 3.2.25 on 2025-09-07 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cenarios', '0005_auto_20250907_0319'),
        ('jogos', '0003_auto_20250906_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='cenario',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='cenarios.cenario'),
        ),
    ]
