# Generated by Django 3.2.25 on 2025-09-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('R0D', 'Reprocessar 0→atual'), ('RND', 'Reprocessar 0→atual e liberar próximo'), ('SPA', 'Simular período atual'), ('SPN', 'Simular período atual e liberar próximo'), ('RDA', 'Reprocessar período passado'), ('LPD', 'Liberar próximo período de decisões'), ('CAD', 'Cancelar simulação do último período'), ('RSD', 'Reprocessar 0→atual, simular e liberar próximo')], max_length=3)),
                ('lote_id', models.CharField(max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='jogos.jogo')),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='SimulacaoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('R0D', 'Reprocessar 0→atual'), ('RND', 'Reprocessar 0→atual e liberar próximo'), ('SPA', 'Simular período atual'), ('SPN', 'Simular período atual e liberar próximo'), ('RDA', 'Reprocessar período passado'), ('LPD', 'Liberar próximo período de decisões'), ('CAD', 'Cancelar simulação do último período'), ('RSD', 'Reprocessar 0→atual, simular e liberar próximo')], max_length=3)),
                ('periodo_de', models.PositiveIntegerField()),
                ('periodo_para', models.PositiveIntegerField()),
                ('step_index', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='simulacao.simulacaoexecucao')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='jogos.jogo')),
            ],
            options={
                'ordering': ('requested_at',),
            },
        ),
        migrations.AddIndex(
            model_name='simulacaoperiodo',
            index=models.Index(fields=['jogo', 'requested_at'], name='simulacao_s_jogo_id_563c38_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacaoperiodo',
            index=models.Index(fields=['acao', 'requested_at'], name='simulacao_s_acao_6e6c7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simulacaoperiodo',
            unique_together={('execucao', 'step_index')},
        ),
        migrations.AddIndex(
            model_name='simulacaoexecucao',
            index=models.Index(fields=['jogo', 'requested_at'], name='simulacao_s_jogo_id_fc8919_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacaoexecucao',
            index=models.Index(fields=['acao', 'requested_at'], name='simulacao_s_acao_d51017_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='simulacaoexecucao',
            unique_together={('jogo', 'lote_id')},
        ),
    ]
