# Generated by Django 3.2.25 on 2025-09-05 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cod', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('periodo_atual', models.PositiveIntegerField(default=0)),
                ('status_decisoes_disponiveis', models.BooleanField(default=False)),
                ('cenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='cenarios.produto')),
            ],
        ),
        migrations.CreateModel(
            name='SimulacaoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('R0D', 'Reprocessar 0→atual'), ('RND', 'Reprocessar 0→atual e liberar próximo'), ('SPA', 'Simular período atual'), ('SPN', 'Simular período atual e liberar próximo'), ('RDA', 'Reprocessar período passado'), ('LPD', 'Liberar próximo período de decisões'), ('CAD', 'Cancelar simulação do último período')], max_length=3)),
                ('lote_id', models.CharField(max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='simulacao.jogo')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
                'unique_together': {('jogo', 'lote_id')},
                'index_together': {('jogo', 'requested_at'), ('acao', 'requested_at')},
            },
        ),
        migrations.CreateModel(
            name='SimulacaoPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('R0D', 'Reprocessar 0→atual'), ('RND', 'Reprocessar 0→atual e liberar próximo'), ('SPA', 'Simular período atual'), ('SPN', 'Simular período atual e liberar próximo'), ('RDA', 'Reprocessar período passado'), ('LPD', 'Liberar próximo período de decisões'), ('CAD', 'Cancelar simulação do último período')], max_length=3)),
                ('periodo_de', models.PositiveIntegerField()),
                ('periodo_para', models.PositiveIntegerField()),
                ('decisoes_de', models.NullBooleanField()),
                ('decisoes_para', models.NullBooleanField()),
                ('step_index', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='simulacao.simulacaoexecucao')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='simulacao.jogo')),
            ],
            options={
                'ordering': ('requested_at',),
                'unique_together': {('execucao', 'step_index')},
                'index_together': {('jogo', 'requested_at'), ('acao', 'requested_at')},
            },
        ),
    ]
