# Generated by Django 3.2.25 on 2025-09-06 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
        ('simulacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='cenario',
        ),
        migrations.AlterField(
            model_name='simulacaoexecucao',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='jogos.jogo'),
        ),
        migrations.AlterField(
            model_name='simulacaoperiodo',
            name='decisoes_de',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacaoperiodo',
            name='decisoes_para',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='simulacaoperiodo',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='jogos.jogo'),
        ),
        migrations.AlterIndexTogether(
            name='simulacaoexecucao',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='simulacaoperiodo',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='simulacaoexecucao',
            index=models.Index(fields=['jogo', 'requested_at'], name='simulacao_s_jogo_id_fc8919_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacaoexecucao',
            index=models.Index(fields=['acao', 'requested_at'], name='simulacao_s_acao_d51017_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacaoperiodo',
            index=models.Index(fields=['jogo', 'requested_at'], name='simulacao_s_jogo_id_563c38_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacaoperiodo',
            index=models.Index(fields=['acao', 'requested_at'], name='simulacao_s_acao_6e6c7d_idx'),
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
