# Generated by Django 3.2.25 on 2025-09-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0002_auto_20250906_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulacaoexecucao',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='simulacaoperiodo',
            name='decisoes_de',
        ),
        migrations.RemoveField(
            model_name='simulacaoperiodo',
            name='decisoes_para',
        ),
        migrations.RemoveField(
            model_name='simulacaoperiodo',
            name='observacoes',
        ),
    ]
