# Generated by Django 3.2.25 on 2025-09-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulacao', '0003_auto_20250907_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacaoexecucao',
            name='acao',
            field=models.CharField(choices=[('R0D', 'Reprocessar 0→atual'), ('RND', 'Reprocessar 0→atual e liberar próximo'), ('SPA', 'Simular período atual'), ('SPN', 'Simular período atual e liberar próximo'), ('RDA', 'Reprocessar período passado'), ('LPD', 'Liberar próximo período de decisões'), ('CAD', 'Cancelar simulação do último período'), ('RSD', 'Reprocessar 0→atual, simular e liberar próximo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='simulacaoperiodo',
            name='acao',
            field=models.CharField(choices=[('R0D', 'Reprocessar 0→atual'), ('RND', 'Reprocessar 0→atual e liberar próximo'), ('SPA', 'Simular período atual'), ('SPN', 'Simular período atual e liberar próximo'), ('RDA', 'Reprocessar período passado'), ('LPD', 'Liberar próximo período de decisões'), ('CAD', 'Cancelar simulação do último período'), ('RSD', 'Reprocessar 0→atual, simular e liberar próximo')], max_length=3),
        ),
    ]
