# Generated by Django 3.2.25 on 2025-09-05 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fornecedor', models.CharField(max_length=100)),
                ('forma_pagamento', models.CharField(choices=[('avista', 'À Vista'), ('x1', '1 parcela sem entrada'), ('x2', '2 parcelas sem entrada'), ('entrada+1', 'Entrada +1 parcela'), ('entrada+2', 'Entrada +2 parcelas')], max_length=25)),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('insumos', models.ManyToManyField(related_name='produtos', to='cenarios.Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Cenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios', to='cenarios.produto')),
            ],
        ),
    ]
