# Generated by Django 3.2.25 on 2025-10-05 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenario',
            name='criador',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='cenarios_criados', to='authentication.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='criador',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='insumos_criados', to='authentication.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='criador',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='produtos_criados', to='authentication.usuario'),
            preserve_default=False,
        ),
    ]
