# Generated by Django 3.2.25 on 2025-09-05 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cenarios', '0003_alter_cenario_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cenario',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenarios', to='cenarios.produto'),
        ),
    ]
