# Generated by Django 3.2.25 on 2025-09-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cenarios', '0004_alter_cenario_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('avista', 'À Vista'), ('x1', '1 parcela sem entrada'), ('x2', '2 parcelas sem entrada'), ('entrada+1', 'Entrada +1 parcela'), ('entrada+2', 'Entrada +2 parcelas')], default='avista', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='quantidade',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
