# Generated by Django 3.2.25 on 2025-09-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('jogo', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='jogos.jogo')),
            ],
        ),
    ]
