# Generated by Django 3.2.25 on 2025-09-05 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cenarios', '0001_initial'),
        ('jogo_empresa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoModel',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='cenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='cenarios.cenario'),
        ),
    ]
