# Generated by Django 3.2.25 on 2025-09-06 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
        ('jogo_empresa', '0002_auto_20250905_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='jogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='jogos.jogo'),
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
