# Generated by Django 3.2.25 on 2025-09-06 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0003_auto_20250906_1514'),
        ('jogo_empresa', '0003_auto_20250906_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='jogo',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='jogos.jogo'),
        ),
    ]
